-- MySQL Script generated by MySQL Workbench
-- Mon Feb 22 22:33:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema usuariosPeliculadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema usuariosPeliculadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `usuariosPeliculadb` DEFAULT CHARACTER SET utf8 ;
USE `usuariosPeliculadb` ;

-- -----------------------------------------------------
-- Table `usuariosPeliculadb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuariosPeliculadb`.`Users` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `enable` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuariosPeliculadb`.`Criticas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuariosPeliculadb`.`Criticas` (
  `idcriticas` INT NOT NULL AUTO_INCREMENT,
  `idpelicula` INT NOT NULL,
  `nota` INT NOT NULL,
  `critica` TEXT(250) NOT NULL,
  `fecha` DATE NOT NULL,
  `Users_idusuario` INT NOT NULL,
  PRIMARY KEY (`idcriticas`, `Users_idusuario`),
  INDEX `fk_Criticas_Users1_idx` (`Users_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_Criticas_Users1`
    FOREIGN KEY (`Users_idusuario`)
    REFERENCES `usuariosPeliculadb`.`Users` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuariosPeliculadb`.`Authorities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuariosPeliculadb`.`Authorities` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `authority` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuariosPeliculadb`.`Users_has_Authorities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuariosPeliculadb`.`Users_has_Authorities` (
  `Users_idusuario` INT NOT NULL,
  `Authorities_idRol` INT NOT NULL,
  PRIMARY KEY (`Users_idusuario`, `Authorities_idRol`),
  INDEX `fk_Users_has_Authorities_Authorities1_idx` (`Authorities_idRol` ASC) VISIBLE,
  INDEX `fk_Users_has_Authorities_Users_idx` (`Users_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_Authorities_Users`
    FOREIGN KEY (`Users_idusuario`)
    REFERENCES `usuariosPeliculadb`.`Users` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Authorities_Authorities1`
    FOREIGN KEY (`Authorities_idRol`)
    REFERENCES `usuariosPeliculadb`.`Authorities` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
